eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:9020/eureka
  instance:
    instance-id: ${spring.application.name}:${instanceId:${random.value}}
    preferIpAddress: true
server:
  port: 0
spring:
  cloud:
    config:
      enabled: false
  application:
    name: invoice-service
  data:
    mongodb:
      database: invoiceServcieDb
      uri: mongodb://localhost:27017
  kafka:
    consumer:
      auto-offset-reset: latest
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: '*'
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

